name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pydantic
    
    - name: Verify FastAPI app syntax
      run: |
        python -c "from main import app; print('FastAPI app loaded successfully!')"
    
    - name: Test endpoint structure
      run: |
        python -c "from main import app; assert '/file' in [route.path for route in app.routes]; print('Endpoint /file exists!')"
